my_project/my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls', namespace='products')),
]

my_project/my_shop/productapp/urls.py
from django.urls import path
from .views import ProductsListView

app_name = 'productapp'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('<int:category_pk>', ProductsListView.as_view(), name='category'),
]

my_project/my_shop/productapp/models/categorymodel.py
from django.db import models


class Category(models.Model):
    """
    Модель раздела
    """
    name = models.CharField(max_length=255, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    def __str__(self):
        return self.name

my_project/my_shop/productapp/models/productmodel.py
from django.db import models
from datetime import date
from .categorymodel import Category
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.db.models import Manager


class Product(models.Model):
    """ Модель продукта """

    name = models.CharField(max_length=255, verbose_name='название')
    received_date = models.DateField(default=date.today, verbose_name='дата поступления')
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0, verbose_name='цена')
    unit = models.CharField(max_length=10, verbose_name='единица измерения')
    vendor_name = models.CharField(max_length=255, verbose_name='имя поставщика')
    categories = models.ManyToManyField(Category, verbose_name='разделы', related_name='products')
    site = models.ManyToManyField(Site)
    objects = Manager()
    on_site = CurrentSiteManager('site')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id']

    def __str__(self):
        return self.name

my_project/my_shop/productapp/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Product, Category


class ProductsListView(ListView):
    model = Product
    template_name = 'goods_list.html'

    def get_queryset(self):
        category_pk = self.kwargs.get('category_pk')
        queryset = Product.on_site.select_related('vendor_name').prefetch_related('categories')
        return queryset.all() if not category_pk else queryset.filter(categories__id__contains=category_pk)

my_project/my_shop/my_shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<div>
    <nav>
        <div>
            <a href="{% url 'products:index' %}">{{ site.name }}}</a>
        </div>
    </nav>
</div>

<div style="display: flex;">

    <div>
    <a href="{% url 'products:index' %}">Смотреть все</a>
        {% for category in category_list %}
            <a href="{% url 'products:category' category.id %}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <div style="padding: 15px; width: 100%;">
        {% block page_content %} {% endblock %}
    </div>

</div>

{% block page_content %} {% endblock %}

</body>
</html>

my_project/my_shop/productapp/templates/goods_list.html
{% extends 'base.html' %}

{% block page_content %}
    <table class="table table-bordered">
        <thead>
        <tr class="table-primary">
            <th>Название</th>
            <th>Дата поступления</th>
            <th>Цена</th>
            <th>Единица измерения</th>
            <th>Поставщик</th>
            <th>Разделы</th>
        </tr>
        </thead>
        <tbody>
        {% for product in object_list %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.received_date }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.unit }}</td>
                <td>{{ product.vendor_name}}</td>
                <td>{% for category in product.categories.all %} {{ category.name }} <br> {% endfor %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button type="button" style="background-color:red">Добавить товар</button>
{% endblock %}